packages:
  - apps/*
  - packages/*

allowBuilds:
  '@mongodb-js/zstd': false
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  node-liblzma: false
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - eve@0.22.4
