import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseAllDocuments, stringify } from "yaml";
import {
  toolboxToolScopes,
  type ToolboxToolName,
} from "@agent-template/toolbox-config";

type ToolboxEntry = Record<string, unknown>;

const repositoryRoot = fileURLToPath(new URL("..", import.meta.url));
const sourcePath = join(repositoryRoot, "apps/toolbox/tools.yaml");
const outputPath = join(
  repositoryRoot,
  "generated/toolbox-production/tools.yaml",
);
const checkOnly = process.argv.includes("--check");
const authServiceName = "agent-template-oidc";

const documents = parseAllDocuments(readFileSync(sourcePath, "utf8"));
const entries = documents.map((document, index) => {
  if (document.errors.length > 0) {
    throw new Error(
      `Toolbox config document ${index + 1} is invalid: ${document.errors
        .map((error) => error.message)
        .join("; ")}`,
    );
  }

  const value = document.toJS({ maxAliasCount: 100 }) as unknown;
  if (!isRecord(value)) {
    throw new Error(`Toolbox config document ${index + 1} must be an object`);
  }
  return value;
});

const productionEntries: ToolboxEntry[] = [
  {
    audience: "${TOOLBOX_OIDC_AUDIENCE}",
    authorizationServer: "${TOOLBOX_OIDC_ISSUER}",
    kind: "authService",
    mcpEnabled: true,
    name: authServiceName,
    scopesRequired: ["mcp:tools"],
    type: "generic",
  },
  ...entries.map(addProductionAuthorization),
];

const output = [
  "# Generated by scripts/generate-toolbox-production-config.ts. Do not edit.",
  productionEntries
    .map((entry) => stringify(entry, { lineWidth: 0 }).trimEnd())
    .join("\n---\n"),
  "",
].join("\n");

if (checkOnly) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== output) {
    throw new Error(
      "Production Toolbox config is stale. Run pnpm toolbox:generate:production.",
    );
  }
  console.log("Production Toolbox OIDC config is current.");
} else {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, output);
  console.log(`Generated ${outputPath}`);
}

function isRecord(value: unknown): value is ToolboxEntry {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function addProductionAuthorization(entry: ToolboxEntry): ToolboxEntry {
  if (entry.kind !== "tool") return entry;

  const name = String(entry.name);
  if (!Object.hasOwn(toolboxToolScopes, name)) {
    throw new Error(`Toolbox production scope is not classified for ${name}`);
  }

  return {
    ...entry,
    authRequired: [authServiceName],
    scopesRequired: [toolboxToolScopes[name as ToolboxToolName]],
  };
}
